name : CI Pipeline


on:
  push:
    branches:
      - master  # Exécute le pipeline sur chaque commit dans master
  pull_request:
    branches:
      - master  # Exécute le pipeline sur chaque pull request vers master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    -name: Checkout repository
      uses: actions/checkout@v3  # Récupère le code source du repository
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Version de Python à utiliser

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Lancer le linting avec Flake8
    - name: Run Flake8
      run: |
        pip install flake8
        flake8 . 

    # Lancer les tests unitaires
    - name: Run tests with pytest
      run: |
        pip install pytest pytest-cov
        pytest --cov=. --cov-report=term-missing
